packages:
  - "apps/*"
  - "libs/*"

catalog:
  prettier: ^3.6.2
  tsdown: ^0.16.3
  typescript: ^5.9.3
  vitest: ^3.2.4

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - better-sqlite3
