/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectNameRouteImport } from './routes/projects.$projectName'
import { Route as AnalysesAnalysisIdRouteImport } from './routes/analyses.$analysisId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectNameRoute = ProjectsProjectNameRouteImport.update({
  id: '/projects/$projectName',
  path: '/projects/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesAnalysisIdRoute = AnalysesAnalysisIdRouteImport.update({
  id: '/analyses/$analysisId',
  path: '/analyses/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/analyses/$analysisId'
    | '/projects/$projectName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/analyses/$analysisId' | '/projects/$projectName'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/analyses/$analysisId'
    | '/projects/$projectName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AnalysesAnalysisIdRoute: typeof AnalysesAnalysisIdRoute
  ProjectsProjectNameRoute: typeof ProjectsProjectNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectName': {
      id: '/projects/$projectName'
      path: '/projects/$projectName'
      fullPath: '/projects/$projectName'
      preLoaderRoute: typeof ProjectsProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$analysisId': {
      id: '/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof AnalysesAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AnalysesAnalysisIdRoute: AnalysesAnalysisIdRoute,
  ProjectsProjectNameRoute: ProjectsProjectNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
