import { describe, it, expect, beforeEach, vi } from 'vitest';
import { LLMAnalyzer } from './llm-analyzer.js';
import type { SuggestionContext } from '../../suggestions/types.js';
import type { LLMIntegrationConfig } from '../../config/llm.js';
import type { GenerateTextResult } from 'ai';

// Type alias for cleaner test mocking - using Record<string, never> instead of any
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyGenerateTextResult = GenerateTextResult<any, any>;

// Mock the AI SDK
vi.mock('ai', () => ({
  generateText: vi.fn(),
}));

vi.mock('@ai-sdk/openai', () => ({
  createOpenAI: vi.fn(() => vi.fn()),
}));

vi.mock('@ai-sdk/anthropic', () => ({
  createAnthropic: vi.fn(() => vi.fn()),
}));

vi.mock('ollama-ai-provider-v2', () => ({
  ollama: vi.fn(),
}));

const baseConfig: LLMIntegrationConfig = {
  enabled: true,
  provider: 'openai',
  apiKey: 'test-key',
  apiBaseUrl: 'https://example.com',
  model: 'test-model',
  maxTokens: 256,
  temperature: 0.2,
  rateLimitPerMinute: 10,
  requestTimeoutMs: 5000,
  attribution: 'Generated by Test LLM',
};

const baseContext: SuggestionContext = {
  modules: [
    {
      filePath: './src/app.js',
      sourceContent: 'export const foo = 1;',
      fileType: 'js',
      originalSize: 4096,
      bundledSize: 2048,
      isThirdParty: false,
      symbols: [],
      symbolFragments: new Map(),
      exports: ['foo'],
    },
  ],
  dependencies: [
    {
      importerPath: './src/app.js',
      importedPath: './src/util.js',
      type: 'static',
      importedSymbols: ['util'],
    },
  ],
  chunks: [
    {
      name: 'main',
      isEntry: true,
      isAsync: false,
      moduleIds: ['./src/app.js'],
    },
  ],
  bundles: [
    {
      fileName: 'main.js',
      content: 'console.log("hello")',
      type: 'js',
    },
  ],
};

describe('LLMAnalyzer', () => {
  beforeEach(() => {
    // Ensure Map instances are fresh per test
    baseContext.modules[0].symbolFragments = new Map();
    vi.clearAllMocks();
  });

  it('returns empty suggestions when disabled', async () => {
    const analyzer = new LLMAnalyzer({
      config: { ...baseConfig, enabled: false },
    });

    const suggestions = await analyzer.execute(baseContext);
    expect(suggestions).toEqual([]);
  });

  it('parses structured suggestions and appends attribution', async () => {
    const { generateText } = await import('ai');
    vi.mocked(generateText).mockResolvedValueOnce({
      text: JSON.stringify([
        {
          type: 'PERFORMANCE',
          severity: 'warning',
          title: 'Split large module',
          description: 'Consider code-splitting ./src/app.js',
          links: [{ entityType: 'Module', entityPath: './src/app.js' }],
        },
      ]),
      finishReason: 'stop',
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        inputTokens: 0,
        outputTokens: 0,
      },
      experimental_providerMetadata: undefined,
    } as unknown as AnyGenerateTextResult);

    const analyzer = new LLMAnalyzer({ config: baseConfig });
    const suggestions = await analyzer.execute(baseContext);

    expect(suggestions).toHaveLength(1);
    expect(suggestions[0].title).toContain('Split large module');
    expect(suggestions[0].description).toContain('_Generated by Test LLM_');
    expect(generateText).toHaveBeenCalledOnce();
  });

  it('respects rate limits and returns informative suggestion', async () => {
    const { generateText } = await import('ai');
    vi.mocked(generateText).mockResolvedValue({
      text: JSON.stringify([
        {
          type: 'INFO',
          severity: 'info',
          title: 'Initial suggestion',
          description: 'First run',
        },
      ]),
      finishReason: 'stop',
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        inputTokens: 0,
        outputTokens: 0,
      },
      experimental_providerMetadata: undefined,
    } as unknown as AnyGenerateTextResult);

    let currentTime = 0;
    const analyzer = new LLMAnalyzer({
      config: { ...baseConfig, rateLimitPerMinute: 1 },
      now: () => currentTime,
    });

    const first = await analyzer.execute(baseContext);
    expect(first).toHaveLength(1);
    expect(generateText).toHaveBeenCalledTimes(1);

    // Without advancing the clock, the second call should be rate limited
    const second = await analyzer.execute(baseContext);
    expect(second).toHaveLength(1);
    expect(second[0].type).toBe('LLM_RATE_LIMIT');
    expect(generateText).toHaveBeenCalledTimes(1); // Still only one call

    // Advance beyond the rate limit window and ensure calls resume
    currentTime = 120_000;
    await analyzer.execute(baseContext);
    expect(generateText).toHaveBeenCalledTimes(2);
  });

  it('gracefully handles invalid JSON responses', async () => {
    const { generateText } = await import('ai');
    vi.mocked(generateText).mockResolvedValueOnce({
      text: 'not-json',
      finishReason: 'stop',
      usage: {
        promptTokens: 0,
        completionTokens: 0,
        totalTokens: 0,
        inputTokens: 0,
        outputTokens: 0,
      },
      experimental_providerMetadata: undefined,
    } as unknown as AnyGenerateTextResult);

    const analyzer = new LLMAnalyzer({ config: baseConfig });

    const suggestions = await analyzer.execute(baseContext);
    expect(suggestions).toHaveLength(1);
    expect(suggestions[0].type).toBe('LLM_FALLBACK');
  });

  it('gracefully handles errors from generateText', async () => {
    const { generateText } = await import('ai');
    vi.mocked(generateText).mockRejectedValueOnce(new Error('API connection failed'));

    const analyzer = new LLMAnalyzer({ config: baseConfig });

    const suggestions = await analyzer.execute(baseContext);
    expect(suggestions).toHaveLength(1);
    expect(suggestions[0].type).toBe('LLM_FALLBACK');
    expect(suggestions[0].description).toContain('API connection failed');
  });
});
