import { describe, it, expect, beforeEach } from 'vitest';
import { LLMAnalyzer, type LLMClient, type LLMGenerationRequest } from './llm-analyzer.js';
import type { SuggestionContext } from '../../suggestions/types.js';
import type { LLMIntegrationConfig } from '../../config/llm.js';

class StubClient implements LLMClient {
  public calls = 0;

  constructor(
    private readonly provider: string,
    private readonly responses: string[],
  ) {}

  providerName(): string {
    return this.provider;
  }

  async generate(_request: LLMGenerationRequest): Promise<string> {
    this.calls += 1;
    return this.responses[this.calls - 1] ?? '[]';
  }
}

const baseConfig: LLMIntegrationConfig = {
  enabled: true,
  provider: 'openai',
  apiKey: 'test-key',
  apiBaseUrl: 'https://example.com',
  model: 'test-model',
  maxTokens: 256,
  temperature: 0.2,
  rateLimitPerMinute: 10,
  requestTimeoutMs: 5000,
  attribution: 'Generated by Test LLM',
};

const baseContext: SuggestionContext = {
  modules: [
    {
      filePath: './src/app.js',
      sourceContent: 'export const foo = 1;',
      fileType: 'js',
      originalSize: 4096,
      bundledSize: 2048,
      isThirdParty: false,
      symbols: [],
      symbolFragments: new Map(),
      exports: ['foo'],
    },
  ],
  dependencies: [
    {
      importerPath: './src/app.js',
      importedPath: './src/util.js',
      type: 'static',
      importedSymbols: ['util'],
    },
  ],
  chunks: [
    {
      name: 'main',
      isEntry: true,
      isAsync: false,
      moduleIds: ['./src/app.js'],
    },
  ],
  bundles: [
    {
      fileName: 'main.js',
      content: 'console.log("hello")',
      type: 'js',
    },
  ],
};

describe('LLMAnalyzer', () => {
  beforeEach(() => {
    // Ensure Map instances are fresh per test
    baseContext.modules[0].symbolFragments = new Map();
  });

  it('returns empty suggestions when disabled', async () => {
    const analyzer = new LLMAnalyzer({
      config: { ...baseConfig, enabled: false },
      client: new StubClient('Test Provider', []),
    });

    const suggestions = await analyzer.execute(baseContext);
    expect(suggestions).toEqual([]);
  });

  it('parses structured suggestions and appends attribution', async () => {
    const client = new StubClient('Test Provider', [
      JSON.stringify([
        {
          type: 'PERFORMANCE',
          severity: 'warning',
          title: 'Split large module',
          description: 'Consider code-splitting ./src/app.js',
          links: [{ entityType: 'Module', entityPath: './src/app.js' }],
        },
      ]),
    ]);

    const analyzer = new LLMAnalyzer({ config: baseConfig, client });
    const suggestions = await analyzer.execute(baseContext);

    expect(suggestions).toHaveLength(1);
    expect(suggestions[0].title).toContain('Split large module');
    expect(suggestions[0].description).toContain('_Generated by Test LLM_');
    expect(client.calls).toBe(1);
  });

  it('respects rate limits and returns informative suggestion', async () => {
    const client = new StubClient('Test Provider', [
      JSON.stringify([
        {
          type: 'INFO',
          severity: 'info',
          title: 'Initial suggestion',
          description: 'First run',
        },
      ]),
    ]);

    let currentTime = 0;
    const analyzer = new LLMAnalyzer({
      config: { ...baseConfig, rateLimitPerMinute: 1 },
      client,
      now: () => currentTime,
    });

    const first = await analyzer.execute(baseContext);
    expect(first).toHaveLength(1);
    expect(client.calls).toBe(1);

    // Without advancing the clock, the second call should be rate limited
    const second = await analyzer.execute(baseContext);
    expect(second).toHaveLength(1);
    expect(second[0].type).toBe('LLM_RATE_LIMIT');
    expect(client.calls).toBe(1);

    // Advance beyond the rate limit window and ensure calls resume
    currentTime = 120_000;
    await analyzer.execute(baseContext);
    expect(client.calls).toBe(2);
  });

  it('gracefully handles invalid JSON responses', async () => {
    const client = new StubClient('Test Provider', ['not-json']);
    const analyzer = new LLMAnalyzer({ config: baseConfig, client });

    const suggestions = await analyzer.execute(baseContext);
    expect(suggestions).toHaveLength(1);
    expect(suggestions[0].type).toBe('LLM_FALLBACK');
  });
});
